on:
  push:
    branches:
      - source

name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: source
    - run: npm install -y
    - run: npx webpack --env production
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}
